var ibObj;var instagramBrowserNextMax;function instagramFetch(settings){var access_token=settings.accessToken;var param={access_token:access_token};fetchCMD(param,settings)}
function fetchCMD(param,settings){var cmdURL="";if(settings.mode=="user")cmdURL="https://api.instagram.com/v1/users/"+settings.userID+"/media/recent/?callback=?";else if(settings.mode=="popular")cmdURL="https://api.instagram.com/v1/media/popular?callback=?";else if(settings.mode=="location")cmdURL="https://api.instagram.com/v1/locations/"+settings.locationID+"/media/recent/?callback=?";else if(settings.mode=="multiuser"){var userIDArray=settings.userID;userIDArray=userIDArray.split(",");jQuery.each(userIDArray,
function(index){cmdURL="https://api.instagram.com/v1/users/"+userIDArray[index]+"/media/recent/?callback=?";jQuery.getJSON(cmdURL,param,function(data){onPhotoLoaded(data,settings,"off")})});return false}else{var tagQuery=settings.tag.replace(/ /g,"");cmdURL="https://api.instagram.com/v1/tags/"+tagQuery+"/media/recent?callback=?"}jQuery.getJSON(cmdURL,param,function(data){onPhotoLoaded(data,settings)})}
function instagramUserSearch(settings){var access_token=settings.accessToken;var searchQuery=settings.user;var param={access_token:access_token,q:searchQuery};userSearchCMD(param,settings)}function userSearchCMD(param,settings){var cmdURL="https://api.instagram.com/v1/users/search?callback=?";jQuery.getJSON(cmdURL,param,function(data){onUserLoaded(data,settings)})}
function onUserLoaded(data,settings){if(data.meta.code==200){var users=data.data;if(users.length>0)for(var key in users){var user=users[key];var instagramUser="";instagramUser='<div class="instagram-user-all" id="p'+user.id+'" title="'+user.username+'" rel="'+user.id+'">';instagramUser+="<img src='"+user.profile_picture+"' />";instagramUser+="<span class='instagram-username'>"+user.username+"</span>";instagramUser+="<span class='instagram-fullname'>"+user.full_name+"</span>";instagramUser+="</div>";
jQuery(instagramUser).appendTo(ibObj)}}}function instagramTagsLoadMore(settings){var access_token=settings.accessToken;var param={access_token:access_token,max_tag_id:instagramBrowserNextMax};if(settings.mode=="tag")var searchQuery=settings.tag.replace(/ /g,"");loadMoreCMD(settings,param,searchQuery)}
function loadMoreCMD(settings,param,searchQuery){var cmdURL="https://api.instagram.com/v1/tags/"+searchQuery+"/media/recent?callback=?";jQuery.getJSON(cmdURL,param,function(data){onPhotoLoaded(data,settings)})}function instagramUsersLoadMore(settings){var access_token=settings.accessToken;var param={access_token:access_token,max_id:instagramBrowserNextMax};loadMoreUsersCMD(settings,param)}
function loadMoreUsersCMD(settings,param){var cmdURL="https://api.instagram.com/v1/users/"+settings.userID+"/media/recent/?callback=?";jQuery.getJSON(cmdURL,param,function(data){onPhotoLoaded(data,settings)})}function instagramLocationLoadMore(settings){var access_token=settings.accessToken;var param={access_token:access_token,max_id:instagramBrowserNextMax};loadMoreLocationsCMD(settings,param)}
function loadMoreLocationsCMD(settings,param){var cmdURL="https://api.instagram.com/v1/locations/"+settings.locationID+"/media/recent/?callback=?";jQuery.getJSON(cmdURL,param,function(data){onPhotoLoaded(data,settings)})}
function onPhotoLoaded(data,settings,loadMoreBool){if(settings.galleryFullscreenPhotos!=""&&settings.galleryMode=="fullscreen"){displayGalleryByType(settings);return false}if(data.pagination)if(data.pagination.next_max_id)instagramBrowserNextMax=data.pagination.next_max_id;else instagramBrowserNextMax="Empty";else instagramBrowserNextMax="Empty";if(data.meta.code==200){var photos=data.data;if(ibObj.html()!="")var addingToList=true;else var addingToList=false;if(photos.length>0){for(var key in photos){var photo=
photos[key];var instagramPhoto="";var photoCaption="";if(photo.caption)photoCaption=photo.caption.text;else photoCaption="Instagram Photo";if(photo.link==null)photo.link="http://instagram.com/p/";instagramPhoto='<a class="instagram-photo" href="'+photo.images.standard_resolution.url+'" data-url="'+photo.link+'" data-name="'+photo.user.full_name+'" id="p'+photo.id+'" title="'+photoCaption+" ("+photo.likes.count+" Likes) &lt;a href=&quot;"+photo.link+'&quot;&gt;View Photo&lt;/a&gt; " data-created="'+
photo.created_time+'" rel="group">';instagramPhoto+='<img src="'+photo.images.standard_resolution.url+'" width="100%">';instagramPhoto+="</a>";jQuery(instagramPhoto).appendTo(ibObj)}var photoCount=jQuery(".instagram-photo").size()-1;if(addingToList==false)jQuery(".instagram-photo").hide();jQuery(".instagram-photo").each(function(index){currentPhoto=jQuery(this);currentPhoto.delay(settings.delayInterval*index).fadeIn(settings.speed);jQuery("#seachInstagramLoadMoreContainer").remove();if(index==photoCount&&
instagramBrowserNextMax!="Empty")jQuery('<div id="seachInstagramLoadMoreContainer"><a class="seachInstagramLoadMore btn btn-inverse">Load More</a></div>').appendTo(ibObj);if(loadMoreBool=="off")jQuery("#seachInstagramLoadMoreContainer").remove()});displayGalleryByType(settings)}else alert("empty")}else alert(data.meta.error_message)}
function displayGalleryByType(settings){if(settings.galleryMode=="fullscreen"){var images=[];if(settings.galleryFullscreenPhotos!="")jQuery(settings.galleryFullscreenPhotos+" img").each(function(index){var imageObj={"path":jQuery(this).attr("src"),"title":jQuery(this).attr("title"),"dateTime":jQuery(this).attr("date-created"),"caption":jQuery(this).attr("rel")};images[index]=imageObj});else{jQuery(".instagram-photo").each(function(index){var imageObj={"path":jQuery(this).find("img").attr("src"),"title":jQuery(this).attr("data-name"),
"dateTime":jQuery(this).attr("data-created"),"caption":jQuery(this).attr("title")};images[index]=imageObj});ibObj.hide()}var index=0;jQuery.backstretch(images[index].path,{speed:500});function cycle(){index=index>=images.length-1?0:index+1;if(images[index]){jQuery.backstretch(images[index].path);updateCaption(index)}else index=index-1}function updateCaption(index){if(settings.galleryFullscreenPhotos!="")var obDate=images[index].dateTime;else{var obDate=parseInt(images[index].dateTime);obDate=new Date(obDate*
1E3);obDate=dateFormat(obDate,"dddd, mmmm dS, yyyy, h:MM:ss TT")}var captionContent="<h3>"+images[index].title+"</h3>";captionContent+="<em>"+obDate+"</em>";captionContent+="<p>"+images[index].caption+"</p>";jQuery(".caption-container .content").html(captionContent)}var interval=setInterval(cycle,5E3);jQuery(".photo-nav a.next").click(function(){index=index>=images.length-1?0:index+1;if(images[index]){jQuery.backstretch(images[index].path);updateCaption(index);clearInterval(interval);interval=setInterval(cycle,
7E3)}else index=index-1});jQuery(".photo-nav a.prev").click(function(){index=index>=1?index-1:images.length-1;if(images[index]){jQuery.backstretch(images[index].path);updateCaption(index);clearInterval(interval);interval=setInterval(cycle,7E3)}else index=index+1});updateCaption(index)}if(settings.galleryMode=="thumbnail"){jQuery(".caption-container").hide();jQuery(".photo-nav").hide();jQuery(ibObj).show();startFancybox()}if(settings.galleryMode=="list"){jQuery(".caption-container").hide();jQuery(".photo-nav").hide();
jQuery(ibObj).show().addClass("list");startFancybox()}}function startFancybox(){jQuery(ibObj).find("a.instagram-photo").fancybox({"nextEffect":"fade","prevEffect":"fade","overlayOpacity":0.8,"overlayColor":"#000000","arrows":false,"titlePosition":"inside"})}
jQuery.fn.instagramTheatre=function(options){var settings={mode:"popular",accessToken:"3794301.f59def8.e08bcd8b10614074882b2d1b787e2b6f",userID:"1138644",speed:700,delayInterval:80,tag:"sports",locationID:"41354",galleryMode:"thumbnail",galleryFullscreenPhotos:""};ibObj=jQuery(this);jQuery.extend(settings,options);return this.each(function(){jQuery(document).ready(function(){instagramFetch(settings);jQuery(".seachInstagramLoadMore").live("click",function(){if(settings.mode=="tag")instagramTagsLoadMore(settings);
else if(settings.mode=="user")instagramUsersLoadMore(settings);else if(settings.mode=="location")instagramLocationLoadMore(settings)});jQuery("#searchByTag .submit").click(function(){ibObj.html("");var customSettings=settings;customSettings.mode="tag";customSettings.tag=jQuery("input.searchTag").val().replace(/ /g,"");if(customSettings.tag==""){alert("Please enter a valid hashtag.");return false}instagramFetch(customSettings);return false});jQuery("#searchByUser .submit").click(function(){ibObj.html("");
var customSettings=settings;customSettings.mode="user";customSettings.user=jQuery("input.searchUser").val().replace(/ /g,"");if(customSettings.user==""){alert("Please enter a valid username.");return false}instagramUserSearch(customSettings);return false});jQuery("#searchByLocation .submit").click(function(){ibObj.html("");var customSettings=settings;customSettings.mode="location";customSettings.locationID=jQuery("select.searchLocation").val().replace(/ /g,"");if(customSettings.locationID==""){alert("Please enter a valid location.");
return false}instagramFetch(customSettings);return false});jQuery(".instagram-user-all").live("click",function(){ibObj.html("");var customSettings=settings;customSettings.mode="user";customSettings.userID=jQuery(this).attr("rel");instagramFetch(customSettings)});jQuery(".list .instagram-photo").live({mouseenter:function(){var thisPhoto=jQuery(this);var obHeight=thisPhoto.height();var obWidth=thisPhoto.width();var obDate=parseInt(thisPhoto.attr("data-created"));obDate=new Date(obDate*1E3);obDate=dateFormat(obDate,
"dddd, mmmm dS, yyyy, h:MM:ss TT");var photoDesc='<div class="instagram-hover-cover">';photoDesc+="<h3>"+thisPhoto.attr("data-name")+"</h3>";photoDesc+="<em>"+obDate+"</em>";photoDesc+="<p>"+thisPhoto.attr("title").substring(0,196)+"</p>";photoDesc+="</div>";thisPhoto.append(photoDesc);jQuery(".instagram-hover-cover").hide().css({"height":"164px","width":obWidth}).slideDown("fast")},mouseleave:function(){var thisPhoto=jQuery(this);thisPhoto.find(".instagram-hover-cover").delay(500).slideUp("fast",
function(){jQuery(this).remove()})}})})})};